#!/usr/bin/env bash
#
# recover-actors.sh — one-shot recovery for mf-pi actors that cannot be reached
# ("连不上" / blank page / 503 at the router) after a redeploy, because the
# ActorTemplate's golden base snapshot is defective.
#
# SYMPTOM
#   * Browsing http://<entry>/<user>/ errors or hangs; the router returns
#       503 upstream connect error or disconnect/reset before headers.
#       reset reason: remote connection failure ... delayed connect error: 111
#   * `kubectl ate get actor <user>` says STATUS_RUNNING, but the app container
#     is not actually running (only the `pause` sentinel sandbox is up), so
#     `/<user>/` is refused with ECONNREFUSED.
#   * A brand-new user never starts; resume fails and the actor wedges in
#     STATUS_RESUMING:
#       while running `runsc restore`: exit status 128
#       failed to load kernel: vfs.CompleteRestore() failed: failed to complete
#       restore for filesystem type "9p": failed to walk "skills" ... in mount
#       "mf-agent:/data/pi-agent": no such file or directory
#
# ROOT CAUSE
#   The ActorTemplate's golden base snapshot (regenerated by the controller
#   whenever the immutable ActorTemplate spec is replaced — e.g. the
#   pi-web -> mf-agent container rename) is not restorable for a per-actor
#   external (sticky) volume: runsc cannot complete the 9p mount restore
#   against a freshly provisioned, empty user volume. Restoring it is reported
#   as success for existing actors while leaving their app container down.
#
# RECOVERY (what this script does)
#   1. Clear status.goldenSnapshot on every ActorTemplate in the namespace.
#      The controller treats phase=Ready as a no-op, so nothing regenerates it,
#      and resume now BOOTS FROM SCRATCH instead of restoring the broken
#      snapshot (see cmd/ateapi/internal/controlapi/workflow_resume.go: an
#      empty GoldenSnapshot skips the restore path). This also fixes brand-new
#      users, which currently fail outright.
#   2. For every affected actor: release it if wedged, then delete + recreate it
#      (which drops its own bad snapshot) and resume it. The sticky userdata PV
#      is preserved by design — internal/volume/sticky DeleteVolume keeps the
#      backing directory and a recreate re-attaches it — so chat history,
#      skills, projects and auth.json survive. The user keeps their password.
#   3. Verify every recovered actor actually serves (HTTP 200 through the
#      router, which bypasses nginx auth).
#
# COST
#   Until the golden base is fixed for real, the FIRST resume of each actor is
#   a cold boot (~25-40s) instead of a fast snapshot restore; the "Agent 正在
#   载入" loading page covers that wait for browsers. Later suspend/resume
#   cycles still use the actor's own (healthy) snapshot and stay fast.
#
# Usage:
#   ./recover-actors.sh                  # recover every NON-SERVING actor (prod)
#   ./recover-actors.sh --test           # same, against the test environment
#   ./recover-actors.sh --all            # recreate every actor, serving or not
#   ./recover-actors.sh --dry-run        # print the plan and change nothing
#   ./recover-actors.sh -y               # non-interactive (no confirmation)
#   ./recover-actors.sh alice tom        # only these users
#   ./recover-actors.sh --skip-golden    # leave golden snapshots untouched
#
# Environment overrides:
#   MFPI_ATESPACE / MFPI_NAMESPACE / MFPI_ROUTER / MFPI_TEMPLATE / MFPI_FORCE
#   KUBECTL_ATE   force the kubectl-ate binary/command
#
# Requires a reachable cluster and the deployment applied (./deploy.sh).
# The router port-forward from ./run-nginx.sh (localhost:58680; 59880 with
# --test) is used for the "is it actually serving?" check; without it the
# script cannot tell broken actors from healthy ones and refuses to guess.

set -uo pipefail
cd "$(dirname "$0")"

# --- Flags ------------------------------------------------------------------
TEST=0
ASSUME_YES=0
DRY_RUN=0
ALL=0
SKIP_GOLDEN=0
USERS=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --test)        TEST=1 ;;
    -y|--yes)      ASSUME_YES=1 ;;
    --force)       ASSUME_YES=1 ;;
    --dry-run)     DRY_RUN=1 ;;
    --all)         ALL=1 ;;
    --skip-golden) SKIP_GOLDEN=1 ;;
    -h|--help)     grep '^#' "$0" | sed 's/^#\{1,2\} //' | sed '/^$/q'; exit 0 ;;
    -*)            echo "unknown flag: $1" >&2; exit 2 ;;
    *)             USERS+=("$1") ;;
  esac
  shift
done
[[ "${MFPI_FORCE:-0}" == "1" ]] && ASSUME_YES=1

# --- Configurable defaults --------------------------------------------------
if (( TEST )); then
  ATESPACE="${MFPI_ATESPACE:-mfpi-test}"
  NAMESPACE="${MFPI_NAMESPACE:-ate-demo-mf-pi-test}"
  ROUTER="${MFPI_ROUTER:-localhost:59880}"
  TEMPLATE_DEFAULT="${MFPI_TEMPLATE:-ate-demo-mf-pi-test/mf-pi}"
  ENTRY="${MFPI_ENTRY:-localhost:59681}"
  ENV_LABEL="TEST"
else
  ATESPACE="${MFPI_ATESPACE:-mfpi}"
  NAMESPACE="${MFPI_NAMESPACE:-ate-demo-mf-pi}"
  ROUTER="${MFPI_ROUTER:-localhost:58680}"
  TEMPLATE_DEFAULT="${MFPI_TEMPLATE:-ate-demo-mf-pi/mf-pi}"
  ENTRY="${MFPI_ENTRY:-localhost:58681}"
  ENV_LABEL="PRODUCTION"
fi

# --- kubectl-ate resolution (same convention as refresh-actor.sh) -----------
if [[ -n "${KUBECTL_ATE:-}" ]]; then
  read -r -a KUBECTL_ATE_CMD <<<"${KUBECTL_ATE}"
elif command -v kubectl-ate >/dev/null 2>&1; then
  KUBECTL_ATE_CMD=(kubectl-ate)
else
  KUBECTL_ATE_CMD=(kubectl ate)
fi

PASS=0
FAIL=0
log() { printf '[recover-actors] %s\n' "$*" >&2; }
ok()  { PASS=$((PASS+1)); log "PASS: $*"; }
bad() { FAIL=$((FAIL+1)); log "FAIL: $*"; }

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || { echo "required command '$1' not found on PATH" >&2; exit 1; }
}
need_cmd kubectl
need_cmd "${KUBECTL_ATE_CMD[0]}"
need_cmd curl
need_cmd jq

if ! kubectl get namespace "${NAMESPACE}" >/dev/null 2>&1; then
  log "SKIP: namespace '${NAMESPACE}' not reachable (no live cluster?) — exiting 0"
  exit 0
fi

# --- Actor helpers ----------------------------------------------------------
actor_json() { # <user>
  "${KUBECTL_ATE_CMD[@]}" get actor "$1" -a "${ATESPACE}" -o json 2>/dev/null
}
actor_field() { # <user> <jq-field>
  actor_json "$1" | jq -r ".actors[0].$2 // empty" 2>/dev/null
}
get_status() { actor_field "$1" status; }
get_template() { # "<ns>/<name>" of the actor's current template, or empty
  local ns nm
  ns="$(actor_field "$1" actorTemplateNamespace)"
  nm="$(actor_field "$1" actorTemplateName)"
  if [[ -n "${ns}" && -n "${nm}" ]]; then printf '%s/%s' "${ns}" "${nm}"; fi
}
list_actors() { # one actor name per line, in the atespace
  "${KUBECTL_ATE_CMD[@]}" get actor -a "${ATESPACE}" -o json 2>/dev/null \
    | jq -r '.actors[]?.metadata.name' 2>/dev/null
}

wait_for_status() { # <user> <target> <timeout-seconds>
  local user="$1" target="$2" timeout="$3" i=0 st
  while (( i < timeout )); do
    st="$(get_status "${user}")"
    [[ "$st" == "$target" ]] && return 0
    sleep 2; i=$((i+2))
  done
  return 1
}

wait_for_any_status() { # <user> <space-separated targets> <timeout-seconds>
  local user="$1" targets="$2" timeout="$3" i=0 st t
  while (( i < timeout )); do
    st="$(get_status "${user}")"
    for t in ${targets}; do [[ "$st" == "$t" ]] && return 0; done
    sleep 2; i=$((i+2))
  done
  return 1
}

# --- Serving check (through the router, bypassing nginx auth) ---------------
router_reachable() {
  local code
  code="$(curl -s -o /dev/null -w '%{http_code}' -m 5 "http://${ROUTER}/" 2>/dev/null || echo 000)"
  [[ "$code" != "000" ]]
}
is_serving() { # <user> -> 0 when the router returns the real app
  local user="$1" tmp code size
  tmp="$(mktemp)"
  code="$(curl -s -o "${tmp}" -w '%{http_code}' -m 8 \
    -H "Host: ${user}.${ATESPACE}.actors.resources.substrate.ate.dev" \
    "http://${ROUTER}/" 2>/dev/null || echo 000)"
  size="$(wc -c <"${tmp}" 2>/dev/null || echo 0)"
  rm -f "${tmp}"
  [[ "$code" == "200" && "${size:-0}" -gt 100 ]]
}
wait_for_serving() { # <user> <timeout-seconds>
  local user="$1" timeout="$2" i=0
  while (( i < timeout )); do
    is_serving "${user}" && return 0
    sleep 5; i=$((i+5))
  done
  return 1
}

if ! router_reachable; then
  log "FATAL: router not reachable at http://${ROUTER}"
  log "       Start it with ./run-nginx.sh (prod) or ./run-nginx-test.sh (--test),"
  log "       or point MFPI_ROUTER at a reachable atenet-router."
  exit 1
fi

# --- Collect templates ------------------------------------------------------
TEMPLATES=()
while IFS= read -r t; do [[ -n "$t" ]] && TEMPLATES+=("$t"); done < <(
  kubectl get actortemplate -n "${NAMESPACE}" -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}' 2>/dev/null
)

if (( ALL )); then MODE_LABEL="recreate ALL actors"; else MODE_LABEL="recreate only NON-SERVING actors"; fi

# --- Pre-flight banner + confirmation --------------------------------------
log "==================================================================="
log " mf-pi actor recovery (${ENV_LABEL})"
log "   atespace  = ${ATESPACE}"
log "   namespace = ${NAMESPACE}"
log "   router    = ${ROUTER} (serving check)"
log "   entry     = ${ENTRY} (informational)"
log "   templates = ${TEMPLATES[*]:-<none>}"
log "   users     = ${USERS[*]:-<all actors>}"
log "   mode      = ${MODE_LABEL}"
if (( SKIP_GOLDEN )); then log "   golden    = left untouched (--skip-golden)"; else log "   golden    = will be cleared"; fi
log " Clearing the golden base + recreating an actor interrupts that user's"
log " running instance. Sticky userdata (/data/pi-agent) is preserved, and"
log " the user keeps their existing password."
log "==================================================================="

if (( DRY_RUN )); then
  log "DRY-RUN: no changes will be made."
elif (( ! ASSUME_YES )); then
  if [[ -t 0 ]]; then
    printf 'Type "yes" to proceed: ' >&2
    read -r REPLY
    [[ "${REPLY,,}" == "yes" ]] || { log "aborted by user."; exit 1; }
  else
    echo "refusing to touch ${ATESPACE} without confirmation:" >&2
    echo "  pass -y/--yes (or set MFPI_FORCE=1) for non-interactive runs." >&2
    exit 1
  fi
fi

# --- Step 1: neutralise the defective golden snapshots ----------------------
# Patching only the field leaves phase=Ready, which is a no-op in the
# controller, so the snapshot is not regenerated and resumes boot from scratch.
clear_golden() {
  local t phase golden
  for t in "${TEMPLATES[@]}"; do
    phase="$(kubectl get actortemplate "$t" -n "${NAMESPACE}" -o jsonpath='{.status.phase}' 2>/dev/null)"
    golden="$(kubectl get actortemplate "$t" -n "${NAMESPACE}" -o jsonpath='{.status.goldenSnapshot}' 2>/dev/null)"
    if [[ -z "${golden}" ]]; then
      log "  ${t}: golden snapshot already empty (phase=${phase:-?}) — nothing to do"
      continue
    fi
    if (( DRY_RUN )); then
      log "  [dry-run] would clear golden snapshot on ${t}"
      continue
    fi
    if kubectl patch actortemplate "$t" -n "${NAMESPACE}" --subresource=status \
         --type=merge -p '{"status":{"goldenSnapshot":""}}' >/dev/null 2>&1; then
      log "  ${t}: cleared golden snapshot -> resumes now boot from scratch"
    else
      bad "${t}: could not clear golden snapshot"
    fi
  done
}

if (( SKIP_GOLDEN )); then
  log "== 1. clear golden snapshots: skipped (--skip-golden) =="
else
  log "== 1. clear defective golden base snapshots =="
  clear_golden
fi

# --- Step 2: recover each affected actor ------------------------------------
release_actor() { # get a wedged actor back to a deletable state
  local user="$1" st pod
  st="$(get_status "${user}")"
  case "${st}" in
    STATUS_SUSPENDED|STATUS_CRASHED|STATUS_PAUSED) return 0 ;;
  esac
  # Fast path: a clean suspend.
  "${KUBECTL_ATE_CMD[@]}" suspend actor "${user}" -a "${ATESPACE}" >/dev/null 2>&1 || true
  wait_for_status "${user}" "STATUS_SUSPENDED" 60 && return 0
  # Wedged (restore keeps failing): drop the bound worker so the pool syncer
  # releases the actor. Its own bad snapshot survives, but we delete + recreate
  # below anyway, which drops it.
  pod="$(actor_field "${user}" ateomPodName)"
  if [[ -n "${pod}" ]]; then
    log "  '${user}' is wedged; deleting worker pod ${pod} to release it"
    kubectl delete pod -n "${NAMESPACE}" "${pod}" --wait=false >/dev/null 2>&1 || true
  fi
  wait_for_any_status "${user}" "STATUS_SUSPENDED STATUS_CRASHED STATUS_PAUSED" 180
}

recover_one() {
  local user="$1" st tpl serving
  st="$(get_status "${user}")"
  if [[ -z "${st}" ]]; then
    bad "actor '${user}' not found in atespace '${ATESPACE}' (skip)"
    return
  fi

  if is_serving "${user}"; then serving="yes"; else serving="no"; fi

  if (( ! ALL )) && [[ "${serving}" == "yes" ]]; then
    ok "actor '${user}' already serving (left untouched)"
    return
  fi

  tpl="$(get_template "${user}")"
  [[ -z "${tpl}" ]] && tpl="${TEMPLATE_DEFAULT}"
  log "actor '${user}': status=${st} template=${tpl} serving=${serving}"

  if (( DRY_RUN )); then
    log "  [dry-run] would: release -> delete -> create --template ${tpl} -> resume -> verify serving"
    ok "[dry-run] plan printed for '${user}'"
    return
  fi

  if ! release_actor "${user}"; then
    bad "actor '${user}' could not be released (last status: $(get_status "${user}"))"
    return
  fi

  "${KUBECTL_ATE_CMD[@]}" delete actor "${user}" -a "${ATESPACE}" >/dev/null 2>&1
  if ! "${KUBECTL_ATE_CMD[@]}" create actor "${user}" -a "${ATESPACE}" --template "${tpl}" >/dev/null 2>&1; then
    bad "could not recreate actor '${user}'"
    return
  fi
  "${KUBECTL_ATE_CMD[@]}" resume actor "${user}" -a "${ATESPACE}" >/dev/null 2>&1 || true

  if ! wait_for_status "${user}" "STATUS_RUNNING" 300; then
    bad "actor '${user}' did not reach STATUS_RUNNING (last: $(get_status "${user}"))"
    return
  fi

  if wait_for_serving "${user}" 240; then
    ok "actor '${user}' recreated, RUNNING and serving (sticky data preserved)"
  else
    bad "actor '${user}' is RUNNING but not serving (check the worker logs)"
  fi
}

log "== 2. recover affected actors =="
TARGETS=()
if (( ${#USERS[@]} )); then
  TARGETS=("${USERS[@]}")
else
  while IFS= read -r name; do
    [[ -n "${name}" ]] && TARGETS+=("${name}")
  done < <(list_actors)
  if (( ${#TARGETS[@]} == 0 )); then
    log "no actors found in atespace '${ATESPACE}'"
  fi
fi

for u in ${TARGETS[@]+"${TARGETS[@]}"}; do
  recover_one "${u}"
done

# --- Step 3: final verification sweep ---------------------------------------
if (( DRY_RUN )); then
  log "== 3. verification skipped (dry-run) =="
else
  log "== 3. verification =="
  for u in ${TARGETS[@]+"${TARGETS[@]}"}; do
    st="$(get_status "${u}")"
    if [[ "${st}" == "STATUS_RUNNING" ]] && is_serving "${u}"; then
      log "  ${u}: RUNNING + serving"
    else
      log "  ${u}: status=${st:-?} serving=no"
      FAIL=$((FAIL+1))
    fi
  done
fi

log "-------------------------------------------------------------------"
if (( FAIL == 0 )); then
  log "RESULT: PASS (${PASS} passed, ${FAIL} failed)"
  exit 0
fi
log "RESULT: FAIL (${PASS} passed, ${FAIL} failed)"
exit 1
